s/echo/log

diff --git a/publish-crates b/publish-crates
--- a/publish-crates
+++ b/publish-crates
@@ -267,12 +267,12 @@ check_cratesio_crate() {
   owners_response="$(curl -sSLf "$owners_url")" || exit_code=$?
   case "$exit_code" in
     22) # 404 response, which means that the crate doesn't exist on crates.io
-      >&2 echo "Crate $crate does not yet exist on crates.io, as per $owners_url. Please request for the crate name to be reserved in advance."
+      >&2 log "Crate $crate does not yet exist on crates.io, as per $owners_url. Please request for the crate name to be reserved in advance."
       return 1
     ;;
     0) ;;
     *)
-      >&2 echo "Request to $owners_url failed with exit code $exit_code"
+      >&2 log "Request to $owners_url failed with exit code $exit_code"
       return 1
     ;;
   esac
@@ -289,7 +289,7 @@ check_cratesio_crate() {
   done < <(echo "$owners_logins")
 
   if [ ! "${found_owner:-}" ]; then
-    >&2 echo "crates.io ownership for crate $crate (from $crate_manifest) is not set up as expected.
+    >&2 log "crates.io ownership for crate $crate (from $crate_manifest) is not set up as expected.
 
 The current owners were recognized from $owners_url:
 $owners_logins
